### ISSUE TITLE
[Feature Request] Import / Export

### ISSUE THREAD

**Issue by Hatbringer** [mezoahmedii/picker#13]
The ability to export and import items from a text file would be highly useful.

**Comment by mezoahmedii** [comment]
Sure, I will add this in the next update

**Comment by tfuxu** [comment]
Import from [Wheel of Names](https://wheelofnames.com/) would also be really useful and should be trivial to implement. 
They use standard JSON, and the only relevant part for Picker would be `entries` object, as it contains the list of things.

Here's a basic parser:
```python
import json

entries: list = []

with open("test.json", "r") as f:
    data = json.load(f)

for entry in data["entries"]:
    entries.append(entry["text"])

print(entries)
```

And a test file: [test.json](https://github.com/user-attachments/files/17451182/test.json)

**Comment by mezoahmedii** [comment]
I added the ability to open a text file in the newest version (v1.1.0), I might add importing from other websites in a future update

**Comment by tfuxu** [comment]
@mezoahmedii The importer/exporter for `Wheel of Names` works great! I think this issue can be closed, as everything here has been resolved.
